### ISSUE TITLE
Add a link back to the GitHub repository

### ISSUE THREAD

**Issue by Moguri** [ArsThaumaturgis/Panda3DTutorial.io#1]
There should be a link somewhere (maybe about?) back to this GitHub repository along with encouragement to file issues and create pull requests.

**Comment by rdb** [comment]
Pinging @ArsThaumaturgis on this—guessing he doesn't notice these issues since he doesn't have a watch on this repo.

It would also be great to put a link to the tutorial from the GitHub repo, using the URL field on the main page for the repo, as well as in the README.md.

**Comment by ArsThaumaturgis** [comment]
Oh hey, thanks for the ping! Indeed, I don't think that I even thought of the issue tracker here, let alone realised that I would have to manually watch my own repo to get notifications of issues being posted. ^^;

... I think that I'll go check my other repos, just in case... ^^;

(I'm not much of a GitHub user, quite frankly.)

As to this issue:
Good ideas, both!

Those should all be implemented now, in the following commits:
https://github.com/ArsThaumaturgis/Panda3DTutorial.io/commit/c5d0b9bfd465f2a4498dede0c5d13572e8273be9
https://github.com/ArsThaumaturgis/Panda3DTutorial.io/commit/1f52ffe8ce22cec71a98d53dba8f506306e4656a
(As well as having simply edited the "website" field on the main page, which doesn't seem to count as a commit.)

Do the above changes seem acceptable?

**Comment by Moguri** [comment]
They look good to me, thanks!

As a heads up, users can reopen issues, so you can always close an issue and ask the original poster to reopen the issue if the fix doesn't work for them.

**Comment by ArsThaumaturgis** [comment]
> They look good to me, thanks!

Ah, I'm glad. ^_^



> As a heads up, users can reopen issues, so you can always close an issue and ask the original poster to reopen the issue if the fix doesn't work for them.

That's fair--but I think that I'd prefer to do it the other way around, myself: to first check that the problem is solved, and only then close the issue (or let the original poster do so, as in this case).
