### ISSUE TITLE
Lesson 16 : .ttf files not being loaded during build

### ISSUE THREAD

**Issue by cobracobracobra** [ArsThaumaturgis/Panda3DTutorial.io#12]
```python

# setup.py
"include_patterns"` : [
    "**/*.png",
    "**/*.ogg",
    "**/*.txt",
    "**/*.egg",
    "**/*.ttf", # <-- This line should be added
    "Fonts/*"
],
````
The font file wasn't included during the building process because .ttf files were ignored.
This meant that whenever I ran the unextracted distributable's "Panda-chan and the Endless Horde.exe", the game wouldn't load.

Also in setup.py, it's "macosx_10_9_x86_64" now instead of "macosx_10_6_x86_64".

**Thank you for what is probably the best tutorial I've ever seen!** I've wanted to make 3D versions of my Python rpgs for some time, and I am now confident that going with Panda3D is the right choice. :)

**Comment by ArsThaumaturgis** [comment]
Ah, I'm very glad that you're finding the tutorial so useful, and thank you for the kind words on it! That's heartening to read! :D

As to the font-issue, hmm... The line "Fonts/*" _should_ result in all files within the "Fonts" folder being included--any ttf-files amongst them. Is that not happening?

Of course, it won't include any fonts located in other directories, and on some systems capitalisation might be a problem should the folder be named "fonts" (i.e. having a lower-case "f"). However, for the folder-arrangement described by the tutorial, that shouldn't be a problem.

As to the Mac issue, thank you for letting me know! I have an unrelated minor update that I've been meaning to get around to, so I may include this change with that! ^_^

**Comment by cobracobracobra** [comment]
My bad, I forgot to make the Fonts folder.

**Comment by ArsThaumaturgis** [comment]
That's fair! These things do happen! ^_^
