### ISSUE TITLE
Is there an easy way to put together the file structure to this?

### ISSUE THREAD

**Issue by jfabdo** [ArsThaumaturgis/Panda3DTutorial.io#15]
I have the other two git projects pulled, it's just difficult to find all the right directories and put them where the code expects them to go.

**Comment by ArsThaumaturgis** [comment]
The "Start Here" page attempts to explain it:

In short, the code indicates where a given asset is intended to be (with paths being relative to the project directory).

That said, the textures for the "Panda-chan" model should be in a folder named "textures", while all other model-textures should be in a folder named "tex"; either way, those folders should be within the folder that holds the model. Last, the UI textures should be in a folder named "UI".

So, let me give two examples:

1)
The model named "bambooLaser.egg" (which comes from the main "PandaSampleModels" repository) should be in a folder named "Misc", within a folder named "Models", within the main project directory.

That is, if the project is located at "C:\Projects\PandaTutorial\", then "bambooLaser.egg" would be found in "C:\Projects\PandaTutorial\**Models\Misc\**.

Its texture would then be found in a folder named "tex" within the above-mentioned folder.

2)
The UI texture "health.png" should be found in a folder named "UI", within the main project folder.

All that said, there's very little stopping you from placing the files where you want and changing the code to reflect this, as long as you keep the models' texture files in their expected locations relative to their models.
