### ISSUE TITLE
Lesson 5 - No need to import Task

### ISSUE THREAD

**Issue by Moguri** [ArsThaumaturgis/Panda3DTutorial.io#2]
`cont` (and related members) are available on all `Task` instances, including the one passed in to `update()`. In other words, `task.cont` can be used instead of `Task.cont`, which avoids the need to import `Task` from `direct.task`.

**Comment by ArsThaumaturgis** [comment]
Ah, I see--thank you for that; I wasn't aware that the return values were so available!

I'll fix that then, I intend.

**Comment by ArsThaumaturgis** [comment]
Done, I believe, with the following commit:
https://github.com/ArsThaumaturgis/Panda3DTutorial.io/commit/ce92963547a4f821710d8af1a21dfbf034924516

Do you see any issues with the changes made there?

**Comment by Moguri** [comment]
The changes look good to me, thanks!
