### ISSUE TITLE
Problem With The Assets

### ISSUE THREAD

**Issue by GamerDTK** [ArsThaumaturgis/Panda3DTutorial.io#7]
Ummmm, never mind, i have seen the reference you gave

**Comment by ArsThaumaturgis** [comment]
Hahah, fair enough! I was just about to direct you to that reference; I'm glad that you found it. ^_^

(And thank you for the kind words regarding the tutorial in the original post! I'm glad if it's proving useful. ^_^)

**Comment by GamerDTK** [comment]
> Hahah, fair enough! I was just about to direct you to that reference; I'm glad that you found it. ^_^
> 
> (And thank you for the kind words regarding the tutorial in the original post! I'm glad if it's proving useful. ^_^)

and a big thanks to you for making it, ur my hero, the explanation is very clear

**Comment by ArsThaumaturgis** [comment]
It's my pleasure! ^_^
